CREATE SEQUENCE IF NOT EXISTS revinfo_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE accounts
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version     BIGINT,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    modified_at TIMESTAMP WITHOUT TIME ZONE,
    name        VARCHAR(255),
    first_name  VARCHAR(255),
    login       VARCHAR(255),
    email       VARCHAR(255),
    CONSTRAINT pk_accounts PRIMARY KEY (id)
);

CREATE TABLE accounts_aud
(
    rev        INTEGER NOT NULL,
    revtype    SMALLINT,
    id         BIGINT  NOT NULL,
    name       VARCHAR(255),
    first_name VARCHAR(255),
    login      VARCHAR(255),
    email      VARCHAR(255),
    CONSTRAINT pk_accounts_aud PRIMARY KEY (rev, id)
);

CREATE TABLE revinfo
(
    rev      INTEGER NOT NULL,
    revtstmp BIGINT,
    CONSTRAINT pk_revinfo PRIMARY KEY (rev)
);

ALTER TABLE accounts
    ADD CONSTRAINT uc_accounts_email UNIQUE (email);

ALTER TABLE accounts
    ADD CONSTRAINT uc_accounts_login UNIQUE (login);

ALTER TABLE accounts_aud
    ADD CONSTRAINT FK_ACCOUNTS_AUD_ON_REV FOREIGN KEY (rev) REFERENCES revinfo (rev);