CREATE TABLE task
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version     BIGINT,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    modified_at TIMESTAMP WITHOUT TIME ZONE,
    account_id  BIGINT                                  NOT NULL,
    description VARCHAR(1000),
    subject     VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_task PRIMARY KEY (id)
);

ALTER TABLE task
    ADD CONSTRAINT FK_TASK_ON_ACCOUNT FOREIGN KEY (account_id) REFERENCES accounts (id);